#!/bin/bash
if [ $# -lt 3 ]; then
   echo my_zip.zip your/existing/file_to_add.xml directory_in_zip/file_to_add.xml
   exit
fi

python -c '
import zipfile as zf, sys
z=zf.ZipFile(sys.argv[1], "a")
z.write(sys.argv[2], sys.argv[3])
z.close()' $1 $2 $3

